[project]
name = "rl-intro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.2.3",
    "numpy>=2.4.1",
    "pygame>=2.6.1",
    "torch>=2.9.1",
    "tqdm>=4.67.1",
]
